### ISSUE TITLE
Have you tried installing another Linux on it? Like a fake update? 

### ISSUE THREAD

**Issue by TR-MZ** [dhammon/zosi-hack#2]

**Comment by dhammon** [comment]
I might have gone that route if I wasn't able to crack the root password.  Thanks for checking out the write up!  :)

**Comment by TR-MZ** [comment]
Yub i meant to ask you if you actually did fint the foot password but i guess you didn’t 👍 have a Nice day

**Comment by TR-MZ** [comment]
But great job 👍
